### ISSUE TITLE
Add parameter for type variables spacing

### ISSUE THREAD

**Issue by dspeele** [scala-ide/scalariform#135]
For example:

def writeResponseStore[T : Format](result: T)(implicit request: Request[_]): Result

Note the space before the colon for the type variable but no for the input parameter.

**Comment by jkinkead** [comment]
If I'm reading between the lines a little, my guess is that you're requesting that Scalariform doesn't reformat:
```scala
// Note the spaces around the ":".
def writeResponseStore[T : Format](implicit request: Request[_]): Result
```
Today, it will delete that first space, resulting in:
```scala
// Space follows ":", but gap is removed.
def writeResponseStore[T: Format](implicit request: Request[_]): Result
```
This is due to the handling of the `spaceBeforeColon` parameter - it treats the type parameter colon in the same way as a colon in an argument list or variable declaration.
