### ISSUE TITLE
`DanglingCloseParenthesis` should default to `Preserve`

### ISSUE THREAD

**Issue by jkinkead** [scala-ide/scalariform#199]
This reverts to pre-fork behavior.

Should be milestone 1.0 per #142 .

**Comment by fommil** [comment]
:+1: (as much as I hate to say it)

**Comment by jkinkead** [comment]
I'm working on this now (fixing unit tests).

It's the source of most of the churn in akka & other projects upgrading to the 0.1.6 / 0.1.7 fork.

**Comment by fommil** [comment]
yup, and my work projects :smile: (and ensime... but we are savvy enough to add the config option)

**Comment by ChrisNeveu** [comment]
The pre-fork behavior was actually `Prevent` when `preserveDanglingCloseParenthesis` was `false` (which was [the default](https://github.com/scala-ide/scalariform/tree/1e1315077e832f155664604360579606e5931e0a#preservedanglingcloseparenthesis)).

Defaulting to `Preserve` doesn't change any code formatting when upgrading from `0.1.4` but it *does* change the behavior of Scalariform (since it stops preventing dangling parentheses).

**Comment by jkinkead** [comment]
Awesome, thanks for chiming in!

I'll let @fommil or @sschaef determine if we want to go for zero-churn (`Preserve`), `0.1.4`-compatible (`Prevent`). `Force` being the `0.1.6`-compatible behavior no one seems to want.

I'll note on the PR not to merge until this is resolved.
